### ISSUE TITLE
Cannot use SSL connections in container

### ISSUE THREAD

**Issue by molp** [rycus86/docker-prometheus#1]
Hello,

when trying to scrape a https URL I get the following error:
`x509: failed to load system roots and no roots provided`

I guess the problem is, that the dependency ca-certificates is being deinstalled since it is in the "build-dependencies" apk call. Can you please remove it from there and add it in an extra apk call?

Thanks!

**Comment by rycus86** [comment]
Thanks a lot for the PR, just merged. The `latest` tag should now rebuild with your changes. :tada:
